export const PENDING_DEPLOY_REQUEST = "PENDING_DEPLOY_REQUEST";
export const CANCEL_PENDING_DEPLOY_REQUEST = "CANCEL_PENDING_DEPLOY_REQUEST";
export const REQUEST_DEPLOY = "REQUEST_DEPLOY";
export const RESPONSE_PENDING_DEPLOY = "RESPONSE_PENDING_DEPLOY";
