export default {
  TESTNET: true,
  BASE_AA: "GGLDAQJOMIACSC3WSF7YI47OERBN3LYK", //YYUXXTQ7YCQOXQHU74DID4HTGNV75P47
  TOKEN_REGISTRY_AA_ADDRESS: "ZT2B6UYBAEHDU5M3EM2MSMVA5OC2AHAY",
  LINK_TO_ODEX: "https://testnet.odex.ooo/trade/"
};
